spring:
  application:
    name: short-link-project
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yml
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis}
      stream:
        short-link-stats:
          topic: short-link:stats-stream
          group: short-link:stats-stream:only-group
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
server:
  port: 8001

springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.uestc.shortlink

knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0

short-link:
  stats:
    locale:
      amap-key: ${AMAP_KEY:}
  domain:
    default: surl.com # 本地mock用短链接域名
  goto-domain:
    white-list:
      enable: true
      names: '哔哩哔哩动画，知乎，小红书，掘金，博客园, 豆瓣'
      domains:
        - bilibili.com
        - zhihu.com
        - xiaohongshu.com
        - juejin.cn
        - cnblogs.com
        - douban.com
